{"name": "Test login failure for non-existent user", "status": "passed", "start": 1734711815845, "stop": 1734711815846, "uuid": "8074e1f9-3fe9-40ec-be97-8268235b05d9", "historyId": "8e43a90cdc817ed06c77125200f37c4c", "testCaseId": "8e43a90cdc817ed06c77125200f37c4c", "fullName": "tests.couriers.test_courier_login#test_login_non_existent_user", "labels": [{"name": "feature", "value": "Courier Login"}, {"name": "story", "value": "Login Failure"}, {"name": "parentSuite", "value": "tests.couriers"}, {"name": "suite", "value": "test_courier_login"}, {"name": "host", "value": "KZALANB019"}, {"name": "thread", "value": "18596-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.couriers.test_courier_login"}]}